### ISSUE TITLE
当只绑定一个宿舍时，没有roomlist键，查询绑定房间数值为 0

### ISSUE THREAD

**Issue by snowf14k3** [zuwei522/perfect-campus_electricity-alert#3]
1. 输出echo的body内容（第二次处理的），无roomlist键，脚本读取得到的房间数为 0 
![image](https://github.com/user-attachments/assets/7ecec591-e209-4bc4-8fc4-a4d1fe138aac)
2. 单宿舍绑定，尝试过759(桂电北海校区),只绑定一个宿舍，json内容依旧没有roomlist键
![image](https://github.com/user-attachments/assets/fe6fe6fd-ce0e-4912-aa01-2326dc08eed9)
3. 多宿舍绑定
![image](https://github.com/user-attachments/assets/baec9b1f-d120-4894-b649-6f9f6e2817ea)

**Comment by snowf14k3** [comment]
更正一下，当有只有一个宿舍的时候，没有roomlist键

**Comment by zuwei522** [comment]
这个问题我确实没有注意到，之前测试都是绑定两个宿舍的，感谢pr✨

另外关于只有自己部署捐赠版才可以推送消息到群聊，我之前部署过，但用一段时间后好像掉登录了，个人感觉有点麻烦就没有继续使用了😥
